/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.konnect.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RouteEvent1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8419547176202253036L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RouteEvent1\",\"namespace\":\"org.konnect.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"konnect_entity\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"paths\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"service\",\"type\":{\"type\":\"record\",\"name\":\"Service\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"}]}},{\"name\":\"protocols\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"created_at\",\"type\":\"long\"},{\"name\":\"strip_path\",\"type\":\"boolean\"},{\"name\":\"updated_at\",\"type\":\"long\"},{\"name\":\"path_handling\",\"type\":\"string\"},{\"name\":\"preserve_host\",\"type\":\"boolean\"},{\"name\":\"regex_priority\",\"type\":\"int\"},{\"name\":\"request_buffering\",\"type\":\"boolean\"},{\"name\":\"response_buffering\",\"type\":\"boolean\"},{\"name\":\"https_redirect_status_code\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RouteEvent1> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RouteEvent1> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RouteEvent1> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RouteEvent1> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RouteEvent1> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RouteEvent1 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RouteEvent1 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RouteEvent1 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RouteEvent1 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence konnect_entity;
  private java.lang.CharSequence name;
  private java.util.List<java.lang.CharSequence> paths;
  private org.konnect.avro.Service service;
  private java.util.List<java.lang.CharSequence> protocols;
  private long created_at;
  private boolean strip_path;
  private long updated_at;
  private java.lang.CharSequence path_handling;
  private boolean preserve_host;
  private int regex_priority;
  private boolean request_buffering;
  private boolean response_buffering;
  private int https_redirect_status_code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RouteEvent1() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param konnect_entity The new value for konnect_entity
   * @param name The new value for name
   * @param paths The new value for paths
   * @param service The new value for service
   * @param protocols The new value for protocols
   * @param created_at The new value for created_at
   * @param strip_path The new value for strip_path
   * @param updated_at The new value for updated_at
   * @param path_handling The new value for path_handling
   * @param preserve_host The new value for preserve_host
   * @param regex_priority The new value for regex_priority
   * @param request_buffering The new value for request_buffering
   * @param response_buffering The new value for response_buffering
   * @param https_redirect_status_code The new value for https_redirect_status_code
   */
  public RouteEvent1(java.lang.CharSequence id, java.lang.CharSequence konnect_entity, java.lang.CharSequence name, java.util.List<java.lang.CharSequence> paths, org.konnect.avro.Service service, java.util.List<java.lang.CharSequence> protocols, java.lang.Long created_at, java.lang.Boolean strip_path, java.lang.Long updated_at, java.lang.CharSequence path_handling, java.lang.Boolean preserve_host, java.lang.Integer regex_priority, java.lang.Boolean request_buffering, java.lang.Boolean response_buffering, java.lang.Integer https_redirect_status_code) {
    this.id = id;
    this.konnect_entity = konnect_entity;
    this.name = name;
    this.paths = paths;
    this.service = service;
    this.protocols = protocols;
    this.created_at = created_at;
    this.strip_path = strip_path;
    this.updated_at = updated_at;
    this.path_handling = path_handling;
    this.preserve_host = preserve_host;
    this.regex_priority = regex_priority;
    this.request_buffering = request_buffering;
    this.response_buffering = response_buffering;
    this.https_redirect_status_code = https_redirect_status_code;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return konnect_entity;
    case 2: return name;
    case 3: return paths;
    case 4: return service;
    case 5: return protocols;
    case 6: return created_at;
    case 7: return strip_path;
    case 8: return updated_at;
    case 9: return path_handling;
    case 10: return preserve_host;
    case 11: return regex_priority;
    case 12: return request_buffering;
    case 13: return response_buffering;
    case 14: return https_redirect_status_code;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: konnect_entity = (java.lang.CharSequence)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    case 3: paths = (java.util.List<java.lang.CharSequence>)value$; break;
    case 4: service = (org.konnect.avro.Service)value$; break;
    case 5: protocols = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: created_at = (java.lang.Long)value$; break;
    case 7: strip_path = (java.lang.Boolean)value$; break;
    case 8: updated_at = (java.lang.Long)value$; break;
    case 9: path_handling = (java.lang.CharSequence)value$; break;
    case 10: preserve_host = (java.lang.Boolean)value$; break;
    case 11: regex_priority = (java.lang.Integer)value$; break;
    case 12: request_buffering = (java.lang.Boolean)value$; break;
    case 13: response_buffering = (java.lang.Boolean)value$; break;
    case 14: https_redirect_status_code = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'konnect_entity' field.
   * @return The value of the 'konnect_entity' field.
   */
  public java.lang.CharSequence getKonnectEntity() {
    return konnect_entity;
  }


  /**
   * Sets the value of the 'konnect_entity' field.
   * @param value the value to set.
   */
  public void setKonnectEntity(java.lang.CharSequence value) {
    this.konnect_entity = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'paths' field.
   * @return The value of the 'paths' field.
   */
  public java.util.List<java.lang.CharSequence> getPaths() {
    return paths;
  }


  /**
   * Sets the value of the 'paths' field.
   * @param value the value to set.
   */
  public void setPaths(java.util.List<java.lang.CharSequence> value) {
    this.paths = value;
  }

  /**
   * Gets the value of the 'service' field.
   * @return The value of the 'service' field.
   */
  public org.konnect.avro.Service getService() {
    return service;
  }


  /**
   * Sets the value of the 'service' field.
   * @param value the value to set.
   */
  public void setService(org.konnect.avro.Service value) {
    this.service = value;
  }

  /**
   * Gets the value of the 'protocols' field.
   * @return The value of the 'protocols' field.
   */
  public java.util.List<java.lang.CharSequence> getProtocols() {
    return protocols;
  }


  /**
   * Sets the value of the 'protocols' field.
   * @param value the value to set.
   */
  public void setProtocols(java.util.List<java.lang.CharSequence> value) {
    this.protocols = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public long getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'strip_path' field.
   * @return The value of the 'strip_path' field.
   */
  public boolean getStripPath() {
    return strip_path;
  }


  /**
   * Sets the value of the 'strip_path' field.
   * @param value the value to set.
   */
  public void setStripPath(boolean value) {
    this.strip_path = value;
  }

  /**
   * Gets the value of the 'updated_at' field.
   * @return The value of the 'updated_at' field.
   */
  public long getUpdatedAt() {
    return updated_at;
  }


  /**
   * Sets the value of the 'updated_at' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(long value) {
    this.updated_at = value;
  }

  /**
   * Gets the value of the 'path_handling' field.
   * @return The value of the 'path_handling' field.
   */
  public java.lang.CharSequence getPathHandling() {
    return path_handling;
  }


  /**
   * Sets the value of the 'path_handling' field.
   * @param value the value to set.
   */
  public void setPathHandling(java.lang.CharSequence value) {
    this.path_handling = value;
  }

  /**
   * Gets the value of the 'preserve_host' field.
   * @return The value of the 'preserve_host' field.
   */
  public boolean getPreserveHost() {
    return preserve_host;
  }


  /**
   * Sets the value of the 'preserve_host' field.
   * @param value the value to set.
   */
  public void setPreserveHost(boolean value) {
    this.preserve_host = value;
  }

  /**
   * Gets the value of the 'regex_priority' field.
   * @return The value of the 'regex_priority' field.
   */
  public int getRegexPriority() {
    return regex_priority;
  }


  /**
   * Sets the value of the 'regex_priority' field.
   * @param value the value to set.
   */
  public void setRegexPriority(int value) {
    this.regex_priority = value;
  }

  /**
   * Gets the value of the 'request_buffering' field.
   * @return The value of the 'request_buffering' field.
   */
  public boolean getRequestBuffering() {
    return request_buffering;
  }


  /**
   * Sets the value of the 'request_buffering' field.
   * @param value the value to set.
   */
  public void setRequestBuffering(boolean value) {
    this.request_buffering = value;
  }

  /**
   * Gets the value of the 'response_buffering' field.
   * @return The value of the 'response_buffering' field.
   */
  public boolean getResponseBuffering() {
    return response_buffering;
  }


  /**
   * Sets the value of the 'response_buffering' field.
   * @param value the value to set.
   */
  public void setResponseBuffering(boolean value) {
    this.response_buffering = value;
  }

  /**
   * Gets the value of the 'https_redirect_status_code' field.
   * @return The value of the 'https_redirect_status_code' field.
   */
  public int getHttpsRedirectStatusCode() {
    return https_redirect_status_code;
  }


  /**
   * Sets the value of the 'https_redirect_status_code' field.
   * @param value the value to set.
   */
  public void setHttpsRedirectStatusCode(int value) {
    this.https_redirect_status_code = value;
  }

  /**
   * Creates a new RouteEvent1 RecordBuilder.
   * @return A new RouteEvent1 RecordBuilder
   */
  public static org.konnect.avro.RouteEvent1.Builder newBuilder() {
    return new org.konnect.avro.RouteEvent1.Builder();
  }

  /**
   * Creates a new RouteEvent1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RouteEvent1 RecordBuilder
   */
  public static org.konnect.avro.RouteEvent1.Builder newBuilder(org.konnect.avro.RouteEvent1.Builder other) {
    if (other == null) {
      return new org.konnect.avro.RouteEvent1.Builder();
    } else {
      return new org.konnect.avro.RouteEvent1.Builder(other);
    }
  }

  /**
   * Creates a new RouteEvent1 RecordBuilder by copying an existing RouteEvent1 instance.
   * @param other The existing instance to copy.
   * @return A new RouteEvent1 RecordBuilder
   */
  public static org.konnect.avro.RouteEvent1.Builder newBuilder(org.konnect.avro.RouteEvent1 other) {
    if (other == null) {
      return new org.konnect.avro.RouteEvent1.Builder();
    } else {
      return new org.konnect.avro.RouteEvent1.Builder(other);
    }
  }

  /**
   * RecordBuilder for RouteEvent1 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RouteEvent1>
    implements org.apache.avro.data.RecordBuilder<RouteEvent1> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence konnect_entity;
    private java.lang.CharSequence name;
    private java.util.List<java.lang.CharSequence> paths;
    private org.konnect.avro.Service service;
    private org.konnect.avro.Service.Builder serviceBuilder;
    private java.util.List<java.lang.CharSequence> protocols;
    private long created_at;
    private boolean strip_path;
    private long updated_at;
    private java.lang.CharSequence path_handling;
    private boolean preserve_host;
    private int regex_priority;
    private boolean request_buffering;
    private boolean response_buffering;
    private int https_redirect_status_code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.konnect.avro.RouteEvent1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.konnect_entity)) {
        this.konnect_entity = data().deepCopy(fields()[1].schema(), other.konnect_entity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.paths)) {
        this.paths = data().deepCopy(fields()[3].schema(), other.paths);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.service)) {
        this.service = data().deepCopy(fields()[4].schema(), other.service);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasServiceBuilder()) {
        this.serviceBuilder = org.konnect.avro.Service.newBuilder(other.getServiceBuilder());
      }
      if (isValidValue(fields()[5], other.protocols)) {
        this.protocols = data().deepCopy(fields()[5].schema(), other.protocols);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.created_at)) {
        this.created_at = data().deepCopy(fields()[6].schema(), other.created_at);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.strip_path)) {
        this.strip_path = data().deepCopy(fields()[7].schema(), other.strip_path);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[8].schema(), other.updated_at);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.path_handling)) {
        this.path_handling = data().deepCopy(fields()[9].schema(), other.path_handling);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.preserve_host)) {
        this.preserve_host = data().deepCopy(fields()[10].schema(), other.preserve_host);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.regex_priority)) {
        this.regex_priority = data().deepCopy(fields()[11].schema(), other.regex_priority);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.request_buffering)) {
        this.request_buffering = data().deepCopy(fields()[12].schema(), other.request_buffering);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.response_buffering)) {
        this.response_buffering = data().deepCopy(fields()[13].schema(), other.response_buffering);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.https_redirect_status_code)) {
        this.https_redirect_status_code = data().deepCopy(fields()[14].schema(), other.https_redirect_status_code);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
    }

    /**
     * Creates a Builder by copying an existing RouteEvent1 instance
     * @param other The existing instance to copy.
     */
    private Builder(org.konnect.avro.RouteEvent1 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.konnect_entity)) {
        this.konnect_entity = data().deepCopy(fields()[1].schema(), other.konnect_entity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paths)) {
        this.paths = data().deepCopy(fields()[3].schema(), other.paths);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.service)) {
        this.service = data().deepCopy(fields()[4].schema(), other.service);
        fieldSetFlags()[4] = true;
      }
      this.serviceBuilder = null;
      if (isValidValue(fields()[5], other.protocols)) {
        this.protocols = data().deepCopy(fields()[5].schema(), other.protocols);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.created_at)) {
        this.created_at = data().deepCopy(fields()[6].schema(), other.created_at);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.strip_path)) {
        this.strip_path = data().deepCopy(fields()[7].schema(), other.strip_path);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[8].schema(), other.updated_at);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.path_handling)) {
        this.path_handling = data().deepCopy(fields()[9].schema(), other.path_handling);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.preserve_host)) {
        this.preserve_host = data().deepCopy(fields()[10].schema(), other.preserve_host);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.regex_priority)) {
        this.regex_priority = data().deepCopy(fields()[11].schema(), other.regex_priority);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.request_buffering)) {
        this.request_buffering = data().deepCopy(fields()[12].schema(), other.request_buffering);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.response_buffering)) {
        this.response_buffering = data().deepCopy(fields()[13].schema(), other.response_buffering);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.https_redirect_status_code)) {
        this.https_redirect_status_code = data().deepCopy(fields()[14].schema(), other.https_redirect_status_code);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'konnect_entity' field.
      * @return The value.
      */
    public java.lang.CharSequence getKonnectEntity() {
      return konnect_entity;
    }


    /**
      * Sets the value of the 'konnect_entity' field.
      * @param value The value of 'konnect_entity'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setKonnectEntity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.konnect_entity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'konnect_entity' field has been set.
      * @return True if the 'konnect_entity' field has been set, false otherwise.
      */
    public boolean hasKonnectEntity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'konnect_entity' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearKonnectEntity() {
      konnect_entity = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'paths' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getPaths() {
      return paths;
    }


    /**
      * Sets the value of the 'paths' field.
      * @param value The value of 'paths'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setPaths(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.paths = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'paths' field has been set.
      * @return True if the 'paths' field has been set, false otherwise.
      */
    public boolean hasPaths() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'paths' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearPaths() {
      paths = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'service' field.
      * @return The value.
      */
    public org.konnect.avro.Service getService() {
      return service;
    }


    /**
      * Sets the value of the 'service' field.
      * @param value The value of 'service'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setService(org.konnect.avro.Service value) {
      validate(fields()[4], value);
      this.serviceBuilder = null;
      this.service = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'service' field has been set.
      * @return True if the 'service' field has been set, false otherwise.
      */
    public boolean hasService() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'service' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.konnect.avro.Service.Builder getServiceBuilder() {
      if (serviceBuilder == null) {
        if (hasService()) {
          setServiceBuilder(org.konnect.avro.Service.newBuilder(service));
        } else {
          setServiceBuilder(org.konnect.avro.Service.newBuilder());
        }
      }
      return serviceBuilder;
    }

    /**
     * Sets the Builder instance for the 'service' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.konnect.avro.RouteEvent1.Builder setServiceBuilder(org.konnect.avro.Service.Builder value) {
      clearService();
      serviceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'service' field has an active Builder instance
     * @return True if the 'service' field has an active Builder instance
     */
    public boolean hasServiceBuilder() {
      return serviceBuilder != null;
    }

    /**
      * Clears the value of the 'service' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearService() {
      service = null;
      serviceBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'protocols' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getProtocols() {
      return protocols;
    }


    /**
      * Sets the value of the 'protocols' field.
      * @param value The value of 'protocols'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setProtocols(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.protocols = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'protocols' field has been set.
      * @return True if the 'protocols' field has been set, false otherwise.
      */
    public boolean hasProtocols() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'protocols' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearProtocols() {
      protocols = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setCreatedAt(long value) {
      validate(fields()[6], value);
      this.created_at = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearCreatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'strip_path' field.
      * @return The value.
      */
    public boolean getStripPath() {
      return strip_path;
    }


    /**
      * Sets the value of the 'strip_path' field.
      * @param value The value of 'strip_path'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setStripPath(boolean value) {
      validate(fields()[7], value);
      this.strip_path = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'strip_path' field has been set.
      * @return True if the 'strip_path' field has been set, false otherwise.
      */
    public boolean hasStripPath() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'strip_path' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearStripPath() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'updated_at' field.
      * @return The value.
      */
    public long getUpdatedAt() {
      return updated_at;
    }


    /**
      * Sets the value of the 'updated_at' field.
      * @param value The value of 'updated_at'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setUpdatedAt(long value) {
      validate(fields()[8], value);
      this.updated_at = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'updated_at' field has been set.
      * @return True if the 'updated_at' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'updated_at' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearUpdatedAt() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'path_handling' field.
      * @return The value.
      */
    public java.lang.CharSequence getPathHandling() {
      return path_handling;
    }


    /**
      * Sets the value of the 'path_handling' field.
      * @param value The value of 'path_handling'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setPathHandling(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.path_handling = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'path_handling' field has been set.
      * @return True if the 'path_handling' field has been set, false otherwise.
      */
    public boolean hasPathHandling() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'path_handling' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearPathHandling() {
      path_handling = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'preserve_host' field.
      * @return The value.
      */
    public boolean getPreserveHost() {
      return preserve_host;
    }


    /**
      * Sets the value of the 'preserve_host' field.
      * @param value The value of 'preserve_host'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setPreserveHost(boolean value) {
      validate(fields()[10], value);
      this.preserve_host = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'preserve_host' field has been set.
      * @return True if the 'preserve_host' field has been set, false otherwise.
      */
    public boolean hasPreserveHost() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'preserve_host' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearPreserveHost() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'regex_priority' field.
      * @return The value.
      */
    public int getRegexPriority() {
      return regex_priority;
    }


    /**
      * Sets the value of the 'regex_priority' field.
      * @param value The value of 'regex_priority'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setRegexPriority(int value) {
      validate(fields()[11], value);
      this.regex_priority = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'regex_priority' field has been set.
      * @return True if the 'regex_priority' field has been set, false otherwise.
      */
    public boolean hasRegexPriority() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'regex_priority' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearRegexPriority() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'request_buffering' field.
      * @return The value.
      */
    public boolean getRequestBuffering() {
      return request_buffering;
    }


    /**
      * Sets the value of the 'request_buffering' field.
      * @param value The value of 'request_buffering'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setRequestBuffering(boolean value) {
      validate(fields()[12], value);
      this.request_buffering = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'request_buffering' field has been set.
      * @return True if the 'request_buffering' field has been set, false otherwise.
      */
    public boolean hasRequestBuffering() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'request_buffering' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearRequestBuffering() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'response_buffering' field.
      * @return The value.
      */
    public boolean getResponseBuffering() {
      return response_buffering;
    }


    /**
      * Sets the value of the 'response_buffering' field.
      * @param value The value of 'response_buffering'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setResponseBuffering(boolean value) {
      validate(fields()[13], value);
      this.response_buffering = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'response_buffering' field has been set.
      * @return True if the 'response_buffering' field has been set, false otherwise.
      */
    public boolean hasResponseBuffering() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'response_buffering' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearResponseBuffering() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'https_redirect_status_code' field.
      * @return The value.
      */
    public int getHttpsRedirectStatusCode() {
      return https_redirect_status_code;
    }


    /**
      * Sets the value of the 'https_redirect_status_code' field.
      * @param value The value of 'https_redirect_status_code'.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder setHttpsRedirectStatusCode(int value) {
      validate(fields()[14], value);
      this.https_redirect_status_code = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'https_redirect_status_code' field has been set.
      * @return True if the 'https_redirect_status_code' field has been set, false otherwise.
      */
    public boolean hasHttpsRedirectStatusCode() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'https_redirect_status_code' field.
      * @return This builder.
      */
    public org.konnect.avro.RouteEvent1.Builder clearHttpsRedirectStatusCode() {
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RouteEvent1 build() {
      try {
        RouteEvent1 record = new RouteEvent1();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.konnect_entity = fieldSetFlags()[1] ? this.konnect_entity : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.paths = fieldSetFlags()[3] ? this.paths : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        if (serviceBuilder != null) {
          try {
            record.service = this.serviceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("service"));
            throw e;
          }
        } else {
          record.service = fieldSetFlags()[4] ? this.service : (org.konnect.avro.Service) defaultValue(fields()[4]);
        }
        record.protocols = fieldSetFlags()[5] ? this.protocols : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        record.created_at = fieldSetFlags()[6] ? this.created_at : (java.lang.Long) defaultValue(fields()[6]);
        record.strip_path = fieldSetFlags()[7] ? this.strip_path : (java.lang.Boolean) defaultValue(fields()[7]);
        record.updated_at = fieldSetFlags()[8] ? this.updated_at : (java.lang.Long) defaultValue(fields()[8]);
        record.path_handling = fieldSetFlags()[9] ? this.path_handling : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.preserve_host = fieldSetFlags()[10] ? this.preserve_host : (java.lang.Boolean) defaultValue(fields()[10]);
        record.regex_priority = fieldSetFlags()[11] ? this.regex_priority : (java.lang.Integer) defaultValue(fields()[11]);
        record.request_buffering = fieldSetFlags()[12] ? this.request_buffering : (java.lang.Boolean) defaultValue(fields()[12]);
        record.response_buffering = fieldSetFlags()[13] ? this.response_buffering : (java.lang.Boolean) defaultValue(fields()[13]);
        record.https_redirect_status_code = fieldSetFlags()[14] ? this.https_redirect_status_code : (java.lang.Integer) defaultValue(fields()[14]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RouteEvent1>
    WRITER$ = (org.apache.avro.io.DatumWriter<RouteEvent1>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RouteEvent1>
    READER$ = (org.apache.avro.io.DatumReader<RouteEvent1>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    if (this.konnect_entity == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.konnect_entity);
    }

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    long size0 = this.paths.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.paths) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    this.service.customEncode(out);

    long size1 = this.protocols.size();
    out.writeArrayStart();
    out.setItemCount(size1);
    long actualSize1 = 0;
    for (java.lang.CharSequence e1: this.protocols) {
      actualSize1++;
      out.startItem();
      out.writeString(e1);
    }
    out.writeArrayEnd();
    if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");

    out.writeLong(this.created_at);

    out.writeBoolean(this.strip_path);

    out.writeLong(this.updated_at);

    out.writeString(this.path_handling);

    out.writeBoolean(this.preserve_host);

    out.writeInt(this.regex_priority);

    out.writeBoolean(this.request_buffering);

    out.writeBoolean(this.response_buffering);

    out.writeInt(this.https_redirect_status_code);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.konnect_entity = null;
      } else {
        this.konnect_entity = in.readString(this.konnect_entity instanceof Utf8 ? (Utf8)this.konnect_entity : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
      }

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.paths;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("paths").schema());
        this.paths = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      if (this.service == null) {
        this.service = new org.konnect.avro.Service();
      }
      this.service.customDecode(in);

      long size1 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a1 = this.protocols;
      if (a1 == null) {
        a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("protocols").schema());
        this.protocols = a1;
      } else a1.clear();
      SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
      for ( ; 0 < size1; size1 = in.arrayNext()) {
        for ( ; size1 != 0; size1--) {
          java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
          e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
          a1.add(e1);
        }
      }

      this.created_at = in.readLong();

      this.strip_path = in.readBoolean();

      this.updated_at = in.readLong();

      this.path_handling = in.readString(this.path_handling instanceof Utf8 ? (Utf8)this.path_handling : null);

      this.preserve_host = in.readBoolean();

      this.regex_priority = in.readInt();

      this.request_buffering = in.readBoolean();

      this.response_buffering = in.readBoolean();

      this.https_redirect_status_code = in.readInt();

    } else {
      for (int i = 0; i < 15; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.konnect_entity = null;
          } else {
            this.konnect_entity = in.readString(this.konnect_entity instanceof Utf8 ? (Utf8)this.konnect_entity : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          }
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.paths;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("paths").schema());
            this.paths = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 4:
          if (this.service == null) {
            this.service = new org.konnect.avro.Service();
          }
          this.service.customDecode(in);
          break;

        case 5:
          long size1 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a1 = this.protocols;
          if (a1 == null) {
            a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("protocols").schema());
            this.protocols = a1;
          } else a1.clear();
          SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
          for ( ; 0 < size1; size1 = in.arrayNext()) {
            for ( ; size1 != 0; size1--) {
              java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
              e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
              a1.add(e1);
            }
          }
          break;

        case 6:
          this.created_at = in.readLong();
          break;

        case 7:
          this.strip_path = in.readBoolean();
          break;

        case 8:
          this.updated_at = in.readLong();
          break;

        case 9:
          this.path_handling = in.readString(this.path_handling instanceof Utf8 ? (Utf8)this.path_handling : null);
          break;

        case 10:
          this.preserve_host = in.readBoolean();
          break;

        case 11:
          this.regex_priority = in.readInt();
          break;

        case 12:
          this.request_buffering = in.readBoolean();
          break;

        case 13:
          this.response_buffering = in.readBoolean();
          break;

        case 14:
          this.https_redirect_status_code = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










