/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.konnect.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ServiceEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9178087447611643273L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ServiceEvent\",\"namespace\":\"org.konnect.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"konnect_entity\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"path\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"port\",\"type\":\"long\"},{\"name\":\"tags\",\"type\":[\"null\",{\"type\":\"array\",\"items\":[\"string\"]}]},{\"name\":\"enabled\",\"type\":\"boolean\"},{\"name\":\"retries\",\"type\":\"long\"},{\"name\":\"protocol\",\"type\":\"string\"},{\"name\":\"created_at\",\"type\":\"long\"},{\"name\":\"updated_at\",\"type\":\"long\"},{\"name\":\"read_timeout\",\"type\":\"long\"},{\"name\":\"write_timeout\",\"type\":\"long\"},{\"name\":\"connect_timeout\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ServiceEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ServiceEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ServiceEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ServiceEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ServiceEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ServiceEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ServiceEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ServiceEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ServiceEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence host;
  private java.lang.CharSequence konnect_entity;
  private java.lang.CharSequence name;
  private java.lang.CharSequence path;
  private long port;
  private java.util.List<java.lang.Object> tags;
  private boolean enabled;
  private long retries;
  private java.lang.CharSequence protocol;
  private long created_at;
  private long updated_at;
  private long read_timeout;
  private long write_timeout;
  private long connect_timeout;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ServiceEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param host The new value for host
   * @param konnect_entity The new value for konnect_entity
   * @param name The new value for name
   * @param path The new value for path
   * @param port The new value for port
   * @param tags The new value for tags
   * @param enabled The new value for enabled
   * @param retries The new value for retries
   * @param protocol The new value for protocol
   * @param created_at The new value for created_at
   * @param updated_at The new value for updated_at
   * @param read_timeout The new value for read_timeout
   * @param write_timeout The new value for write_timeout
   * @param connect_timeout The new value for connect_timeout
   */
  public ServiceEvent(java.lang.CharSequence id, java.lang.CharSequence host, java.lang.CharSequence konnect_entity, java.lang.CharSequence name, java.lang.CharSequence path, java.lang.Long port, java.util.List<java.lang.Object> tags, java.lang.Boolean enabled, java.lang.Long retries, java.lang.CharSequence protocol, java.lang.Long created_at, java.lang.Long updated_at, java.lang.Long read_timeout, java.lang.Long write_timeout, java.lang.Long connect_timeout) {
    this.id = id;
    this.host = host;
    this.konnect_entity = konnect_entity;
    this.name = name;
    this.path = path;
    this.port = port;
    this.tags = tags;
    this.enabled = enabled;
    this.retries = retries;
    this.protocol = protocol;
    this.created_at = created_at;
    this.updated_at = updated_at;
    this.read_timeout = read_timeout;
    this.write_timeout = write_timeout;
    this.connect_timeout = connect_timeout;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return host;
    case 2: return konnect_entity;
    case 3: return name;
    case 4: return path;
    case 5: return port;
    case 6: return tags;
    case 7: return enabled;
    case 8: return retries;
    case 9: return protocol;
    case 10: return created_at;
    case 11: return updated_at;
    case 12: return read_timeout;
    case 13: return write_timeout;
    case 14: return connect_timeout;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: host = (java.lang.CharSequence)value$; break;
    case 2: konnect_entity = (java.lang.CharSequence)value$; break;
    case 3: name = (java.lang.CharSequence)value$; break;
    case 4: path = (java.lang.CharSequence)value$; break;
    case 5: port = (java.lang.Long)value$; break;
    case 6: tags = (java.util.List<java.lang.Object>)value$; break;
    case 7: enabled = (java.lang.Boolean)value$; break;
    case 8: retries = (java.lang.Long)value$; break;
    case 9: protocol = (java.lang.CharSequence)value$; break;
    case 10: created_at = (java.lang.Long)value$; break;
    case 11: updated_at = (java.lang.Long)value$; break;
    case 12: read_timeout = (java.lang.Long)value$; break;
    case 13: write_timeout = (java.lang.Long)value$; break;
    case 14: connect_timeout = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'host' field.
   * @return The value of the 'host' field.
   */
  public java.lang.CharSequence getHost() {
    return host;
  }


  /**
   * Sets the value of the 'host' field.
   * @param value the value to set.
   */
  public void setHost(java.lang.CharSequence value) {
    this.host = value;
  }

  /**
   * Gets the value of the 'konnect_entity' field.
   * @return The value of the 'konnect_entity' field.
   */
  public java.lang.CharSequence getKonnectEntity() {
    return konnect_entity;
  }


  /**
   * Sets the value of the 'konnect_entity' field.
   * @param value the value to set.
   */
  public void setKonnectEntity(java.lang.CharSequence value) {
    this.konnect_entity = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'path' field.
   * @return The value of the 'path' field.
   */
  public java.lang.CharSequence getPath() {
    return path;
  }


  /**
   * Sets the value of the 'path' field.
   * @param value the value to set.
   */
  public void setPath(java.lang.CharSequence value) {
    this.path = value;
  }

  /**
   * Gets the value of the 'port' field.
   * @return The value of the 'port' field.
   */
  public long getPort() {
    return port;
  }


  /**
   * Sets the value of the 'port' field.
   * @param value the value to set.
   */
  public void setPort(long value) {
    this.port = value;
  }

  /**
   * Gets the value of the 'tags' field.
   * @return The value of the 'tags' field.
   */
  public java.util.List<java.lang.Object> getTags() {
    return tags;
  }


  /**
   * Sets the value of the 'tags' field.
   * @param value the value to set.
   */
  public void setTags(java.util.List<java.lang.Object> value) {
    this.tags = value;
  }

  /**
   * Gets the value of the 'enabled' field.
   * @return The value of the 'enabled' field.
   */
  public boolean getEnabled() {
    return enabled;
  }


  /**
   * Sets the value of the 'enabled' field.
   * @param value the value to set.
   */
  public void setEnabled(boolean value) {
    this.enabled = value;
  }

  /**
   * Gets the value of the 'retries' field.
   * @return The value of the 'retries' field.
   */
  public long getRetries() {
    return retries;
  }


  /**
   * Sets the value of the 'retries' field.
   * @param value the value to set.
   */
  public void setRetries(long value) {
    this.retries = value;
  }

  /**
   * Gets the value of the 'protocol' field.
   * @return The value of the 'protocol' field.
   */
  public java.lang.CharSequence getProtocol() {
    return protocol;
  }


  /**
   * Sets the value of the 'protocol' field.
   * @param value the value to set.
   */
  public void setProtocol(java.lang.CharSequence value) {
    this.protocol = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public long getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'updated_at' field.
   * @return The value of the 'updated_at' field.
   */
  public long getUpdatedAt() {
    return updated_at;
  }


  /**
   * Sets the value of the 'updated_at' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(long value) {
    this.updated_at = value;
  }

  /**
   * Gets the value of the 'read_timeout' field.
   * @return The value of the 'read_timeout' field.
   */
  public long getReadTimeout() {
    return read_timeout;
  }


  /**
   * Sets the value of the 'read_timeout' field.
   * @param value the value to set.
   */
  public void setReadTimeout(long value) {
    this.read_timeout = value;
  }

  /**
   * Gets the value of the 'write_timeout' field.
   * @return The value of the 'write_timeout' field.
   */
  public long getWriteTimeout() {
    return write_timeout;
  }


  /**
   * Sets the value of the 'write_timeout' field.
   * @param value the value to set.
   */
  public void setWriteTimeout(long value) {
    this.write_timeout = value;
  }

  /**
   * Gets the value of the 'connect_timeout' field.
   * @return The value of the 'connect_timeout' field.
   */
  public long getConnectTimeout() {
    return connect_timeout;
  }


  /**
   * Sets the value of the 'connect_timeout' field.
   * @param value the value to set.
   */
  public void setConnectTimeout(long value) {
    this.connect_timeout = value;
  }

  /**
   * Creates a new ServiceEvent RecordBuilder.
   * @return A new ServiceEvent RecordBuilder
   */
  public static org.konnect.avro.ServiceEvent.Builder newBuilder() {
    return new org.konnect.avro.ServiceEvent.Builder();
  }

  /**
   * Creates a new ServiceEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ServiceEvent RecordBuilder
   */
  public static org.konnect.avro.ServiceEvent.Builder newBuilder(org.konnect.avro.ServiceEvent.Builder other) {
    if (other == null) {
      return new org.konnect.avro.ServiceEvent.Builder();
    } else {
      return new org.konnect.avro.ServiceEvent.Builder(other);
    }
  }

  /**
   * Creates a new ServiceEvent RecordBuilder by copying an existing ServiceEvent instance.
   * @param other The existing instance to copy.
   * @return A new ServiceEvent RecordBuilder
   */
  public static org.konnect.avro.ServiceEvent.Builder newBuilder(org.konnect.avro.ServiceEvent other) {
    if (other == null) {
      return new org.konnect.avro.ServiceEvent.Builder();
    } else {
      return new org.konnect.avro.ServiceEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ServiceEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ServiceEvent>
    implements org.apache.avro.data.RecordBuilder<ServiceEvent> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence host;
    private java.lang.CharSequence konnect_entity;
    private java.lang.CharSequence name;
    private java.lang.CharSequence path;
    private long port;
    private java.util.List<java.lang.Object> tags;
    private boolean enabled;
    private long retries;
    private java.lang.CharSequence protocol;
    private long created_at;
    private long updated_at;
    private long read_timeout;
    private long write_timeout;
    private long connect_timeout;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.konnect.avro.ServiceEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.host)) {
        this.host = data().deepCopy(fields()[1].schema(), other.host);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.konnect_entity)) {
        this.konnect_entity = data().deepCopy(fields()[2].schema(), other.konnect_entity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.path)) {
        this.path = data().deepCopy(fields()[4].schema(), other.path);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.port)) {
        this.port = data().deepCopy(fields()[5].schema(), other.port);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.tags)) {
        this.tags = data().deepCopy(fields()[6].schema(), other.tags);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.enabled)) {
        this.enabled = data().deepCopy(fields()[7].schema(), other.enabled);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.retries)) {
        this.retries = data().deepCopy(fields()[8].schema(), other.retries);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.protocol)) {
        this.protocol = data().deepCopy(fields()[9].schema(), other.protocol);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.created_at)) {
        this.created_at = data().deepCopy(fields()[10].schema(), other.created_at);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[11].schema(), other.updated_at);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.read_timeout)) {
        this.read_timeout = data().deepCopy(fields()[12].schema(), other.read_timeout);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.write_timeout)) {
        this.write_timeout = data().deepCopy(fields()[13].schema(), other.write_timeout);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.connect_timeout)) {
        this.connect_timeout = data().deepCopy(fields()[14].schema(), other.connect_timeout);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
    }

    /**
     * Creates a Builder by copying an existing ServiceEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(org.konnect.avro.ServiceEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.host)) {
        this.host = data().deepCopy(fields()[1].schema(), other.host);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.konnect_entity)) {
        this.konnect_entity = data().deepCopy(fields()[2].schema(), other.konnect_entity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.path)) {
        this.path = data().deepCopy(fields()[4].schema(), other.path);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.port)) {
        this.port = data().deepCopy(fields()[5].schema(), other.port);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tags)) {
        this.tags = data().deepCopy(fields()[6].schema(), other.tags);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.enabled)) {
        this.enabled = data().deepCopy(fields()[7].schema(), other.enabled);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.retries)) {
        this.retries = data().deepCopy(fields()[8].schema(), other.retries);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.protocol)) {
        this.protocol = data().deepCopy(fields()[9].schema(), other.protocol);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.created_at)) {
        this.created_at = data().deepCopy(fields()[10].schema(), other.created_at);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[11].schema(), other.updated_at);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.read_timeout)) {
        this.read_timeout = data().deepCopy(fields()[12].schema(), other.read_timeout);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.write_timeout)) {
        this.write_timeout = data().deepCopy(fields()[13].schema(), other.write_timeout);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.connect_timeout)) {
        this.connect_timeout = data().deepCopy(fields()[14].schema(), other.connect_timeout);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'host' field.
      * @return The value.
      */
    public java.lang.CharSequence getHost() {
      return host;
    }


    /**
      * Sets the value of the 'host' field.
      * @param value The value of 'host'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setHost(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.host = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'host' field has been set.
      * @return True if the 'host' field has been set, false otherwise.
      */
    public boolean hasHost() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'host' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearHost() {
      host = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'konnect_entity' field.
      * @return The value.
      */
    public java.lang.CharSequence getKonnectEntity() {
      return konnect_entity;
    }


    /**
      * Sets the value of the 'konnect_entity' field.
      * @param value The value of 'konnect_entity'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setKonnectEntity(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.konnect_entity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'konnect_entity' field has been set.
      * @return True if the 'konnect_entity' field has been set, false otherwise.
      */
    public boolean hasKonnectEntity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'konnect_entity' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearKonnectEntity() {
      konnect_entity = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'path' field.
      * @return The value.
      */
    public java.lang.CharSequence getPath() {
      return path;
    }


    /**
      * Sets the value of the 'path' field.
      * @param value The value of 'path'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setPath(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.path = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'path' field has been set.
      * @return True if the 'path' field has been set, false otherwise.
      */
    public boolean hasPath() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'path' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearPath() {
      path = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'port' field.
      * @return The value.
      */
    public long getPort() {
      return port;
    }


    /**
      * Sets the value of the 'port' field.
      * @param value The value of 'port'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setPort(long value) {
      validate(fields()[5], value);
      this.port = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'port' field has been set.
      * @return True if the 'port' field has been set, false otherwise.
      */
    public boolean hasPort() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'port' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearPort() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'tags' field.
      * @return The value.
      */
    public java.util.List<java.lang.Object> getTags() {
      return tags;
    }


    /**
      * Sets the value of the 'tags' field.
      * @param value The value of 'tags'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setTags(java.util.List<java.lang.Object> value) {
      validate(fields()[6], value);
      this.tags = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'tags' field has been set.
      * @return True if the 'tags' field has been set, false otherwise.
      */
    public boolean hasTags() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'tags' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearTags() {
      tags = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'enabled' field.
      * @return The value.
      */
    public boolean getEnabled() {
      return enabled;
    }


    /**
      * Sets the value of the 'enabled' field.
      * @param value The value of 'enabled'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setEnabled(boolean value) {
      validate(fields()[7], value);
      this.enabled = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'enabled' field has been set.
      * @return True if the 'enabled' field has been set, false otherwise.
      */
    public boolean hasEnabled() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'enabled' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearEnabled() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'retries' field.
      * @return The value.
      */
    public long getRetries() {
      return retries;
    }


    /**
      * Sets the value of the 'retries' field.
      * @param value The value of 'retries'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setRetries(long value) {
      validate(fields()[8], value);
      this.retries = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'retries' field has been set.
      * @return True if the 'retries' field has been set, false otherwise.
      */
    public boolean hasRetries() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'retries' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearRetries() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'protocol' field.
      * @return The value.
      */
    public java.lang.CharSequence getProtocol() {
      return protocol;
    }


    /**
      * Sets the value of the 'protocol' field.
      * @param value The value of 'protocol'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setProtocol(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.protocol = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'protocol' field has been set.
      * @return True if the 'protocol' field has been set, false otherwise.
      */
    public boolean hasProtocol() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'protocol' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearProtocol() {
      protocol = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setCreatedAt(long value) {
      validate(fields()[10], value);
      this.created_at = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearCreatedAt() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'updated_at' field.
      * @return The value.
      */
    public long getUpdatedAt() {
      return updated_at;
    }


    /**
      * Sets the value of the 'updated_at' field.
      * @param value The value of 'updated_at'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setUpdatedAt(long value) {
      validate(fields()[11], value);
      this.updated_at = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'updated_at' field has been set.
      * @return True if the 'updated_at' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'updated_at' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearUpdatedAt() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'read_timeout' field.
      * @return The value.
      */
    public long getReadTimeout() {
      return read_timeout;
    }


    /**
      * Sets the value of the 'read_timeout' field.
      * @param value The value of 'read_timeout'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setReadTimeout(long value) {
      validate(fields()[12], value);
      this.read_timeout = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'read_timeout' field has been set.
      * @return True if the 'read_timeout' field has been set, false otherwise.
      */
    public boolean hasReadTimeout() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'read_timeout' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearReadTimeout() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'write_timeout' field.
      * @return The value.
      */
    public long getWriteTimeout() {
      return write_timeout;
    }


    /**
      * Sets the value of the 'write_timeout' field.
      * @param value The value of 'write_timeout'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setWriteTimeout(long value) {
      validate(fields()[13], value);
      this.write_timeout = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'write_timeout' field has been set.
      * @return True if the 'write_timeout' field has been set, false otherwise.
      */
    public boolean hasWriteTimeout() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'write_timeout' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearWriteTimeout() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'connect_timeout' field.
      * @return The value.
      */
    public long getConnectTimeout() {
      return connect_timeout;
    }


    /**
      * Sets the value of the 'connect_timeout' field.
      * @param value The value of 'connect_timeout'.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder setConnectTimeout(long value) {
      validate(fields()[14], value);
      this.connect_timeout = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'connect_timeout' field has been set.
      * @return True if the 'connect_timeout' field has been set, false otherwise.
      */
    public boolean hasConnectTimeout() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'connect_timeout' field.
      * @return This builder.
      */
    public org.konnect.avro.ServiceEvent.Builder clearConnectTimeout() {
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ServiceEvent build() {
      try {
        ServiceEvent record = new ServiceEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.host = fieldSetFlags()[1] ? this.host : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.konnect_entity = fieldSetFlags()[2] ? this.konnect_entity : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.name = fieldSetFlags()[3] ? this.name : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.path = fieldSetFlags()[4] ? this.path : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.port = fieldSetFlags()[5] ? this.port : (java.lang.Long) defaultValue(fields()[5]);
        record.tags = fieldSetFlags()[6] ? this.tags : (java.util.List<java.lang.Object>) defaultValue(fields()[6]);
        record.enabled = fieldSetFlags()[7] ? this.enabled : (java.lang.Boolean) defaultValue(fields()[7]);
        record.retries = fieldSetFlags()[8] ? this.retries : (java.lang.Long) defaultValue(fields()[8]);
        record.protocol = fieldSetFlags()[9] ? this.protocol : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.created_at = fieldSetFlags()[10] ? this.created_at : (java.lang.Long) defaultValue(fields()[10]);
        record.updated_at = fieldSetFlags()[11] ? this.updated_at : (java.lang.Long) defaultValue(fields()[11]);
        record.read_timeout = fieldSetFlags()[12] ? this.read_timeout : (java.lang.Long) defaultValue(fields()[12]);
        record.write_timeout = fieldSetFlags()[13] ? this.write_timeout : (java.lang.Long) defaultValue(fields()[13]);
        record.connect_timeout = fieldSetFlags()[14] ? this.connect_timeout : (java.lang.Long) defaultValue(fields()[14]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ServiceEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ServiceEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ServiceEvent>
    READER$ = (org.apache.avro.io.DatumReader<ServiceEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










